platform :ios, '13.0'
use_frameworks!

target 'AndToIos' do
  # WebRTC - Google, BSD lisans, ücretsiz, iOS 13+ destekli
  pod 'GoogleWebRTC', '~> 1.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
